apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoview-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: photo-view

  template:
    metadata:
      labels:
        app: photo-view
        env: stage
    spec:
      containers:
      - image: nginx:latest
        name: nginx-container
        ports:
        - containerPort: 80
